controllers:
<<<<<<< HEAD
    resource: ../src/Controller/
    type: attribute
recuperer:
    path: /secretaire_note_recupere
    controller: App\Controller\NoteController::recupererEleves
    methods: [POST]

=======
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
>>>>>>> origin/master
